# -*- coding: utf-8 -*-
"""EDA_classifying Heart Sounds

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jcqr8hjDUCimL5Zj12E4pPUJ4ga9vh6
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Audio
import os
import numpy as np
import librosa
import librosa.display
from collections import Counter
import glob
import re

"""***SET A***"""

#set A - skim

df = pd.read_csv('/content/drive/MyDrive/dataset/set_a.csv')
print(df.head(50))
print(df.columns)

#set A - random

Audio('/content/drive/MyDrive/dataset/set_a/artifact__201105280851.wav')

#set A - label

label_colA = 'label'
file_colA = 'fname'

#set A - dataset size

total_samples = len(df)

data_path = "/content/drive/MyDrive/dataset/set_a"
file_count = 0

for root, dirs, files in os.walk(data_path):
    file_count += len(files)

total_size = 0
for root, dirs, files in os.walk(data_path):
    for f in files:
        fp = os.path.join(root, f)
        total_size += os.path.getsize(fp)

total_size_mb = total_size / (1024 * 1024)

print("=== DATASET SIZE ===")
print(f"Total samples (rows in metadata): {total_samples}")
print(f"Total files in folder: {file_count}")
print(f"Total dataset size: {total_size_mb:.2f} MB")

#set A - plot pie chart

label_counts = df[label_colA].value_counts()

print("\n=== CLASS DISTRIBUTION ===")
print(label_counts)

label_percent = label_counts / total_samples * 100
print("\n=== PERCENTAGE ===")
print(label_percent)
print(df['label'].value_counts(dropna=False))
plt.figure(figsize=(6,6))

plt.pie(label_counts.values,
        labels=label_counts.index,
        autopct='%1.1f%%')

plt.title("Class Percentage")

plt.show()

# set A - spectrogram

df = df.dropna(subset=["label"])

samples = df.groupby("label").sample(
    n=3,
    random_state=42
)

plt.figure(figsize=(16,20))

for i, (_, row) in enumerate(samples.iterrows(), start=1):
    audio_path = os.path.join(
        "/content/drive/MyDrive/dataset",
        row["fname"]
    )
    y, sr = librosa.load(
        audio_path,
        sr=None
    )
    mel = librosa.feature.melspectrogram(
        y=y,
        sr=sr,
        n_mels=128
    )
    mel_db = librosa.power_to_db(
        mel,
        ref=np.max
    )

    plt.subplot(12,1,i)

    librosa.display.specshow(
        mel_db,
        sr=sr,
        x_axis="time",
        y_axis="mel"
    )

    plt.title(
        f"{row['label']} | {os.path.basename(audio_path)}"
    )
    plt.colorbar(format="%+2.0f dB")

plt.tight_layout()
plt.show()

# set A - sampling rate

audio_folder = "/content/drive/MyDrive/dataset/set_a"

sampling_rates = []

for file in os.listdir(audio_folder):

    if file.endswith(".wav"):

        path = os.path.join(audio_folder, file)

        try:
            sr = librosa.get_samplerate(path)
            sampling_rates.append(sr)

        except Exception as e:
            print(f"Error: {file}")

print("Sampling Rate Distribution")
print(Counter(sampling_rates))

"""***SET B***"""

#set B - skim

df = pd.read_csv('/content/drive/MyDrive/dataset/set_b.csv')
print(df.head(10))
print(df.columns)

#set B - random

Audio("/content/drive/MyDrive/dataset/set_b/extrastole__127_1306764300147_C2.wav")

#set B

label_colB = 'label'
file_colB = 'fname'

#set B - dataset size

total_samples = len(df)

data_path = "/content/drive/MyDrive/dataset/set_b"
file_count = 0

for root, dirs, files in os.walk(data_path):
    file_count += len(files)

total_size = 0
for root, dirs, files in os.walk(data_path):
    for f in files:
        fp = os.path.join(root, f)
        total_size += os.path.getsize(fp)

total_size_mb = total_size / (1024 * 1024)

print("=== DATASET SIZE ===")
print(f"Total samples (rows in metadata): {total_samples}")
print(f"Total files in folder: {file_count}")
print(f"Total dataset size: {total_size_mb:.2f} MB")

#set B - plot pie chart

label_counts = df[label_colB].value_counts()

print("\n=== CLASS DISTRIBUTION ===")
print(label_counts)

label_percent = label_counts / total_samples * 100
print("\n=== PERCENTAGE ===")
print(label_percent)
print(df['label'].value_counts(dropna=False))
plt.figure(figsize=(6,6))

plt.pie(label_counts.values,
        labels=label_counts.index,
        autopct='%1.1f%%')

plt.title("Class Percentage")

plt.show()

# set B - spectrogram

df = pd.read_csv("/content/drive/MyDrive/dataset/set_b.csv")
files_in_set_b = os.listdir("/content/drive/MyDrive/dataset/set_b")

def get_audio_path(fname):
    base = os.path.basename(fname)
    m = re.search(r'\d{10,}', base)
    if not m:
        return None
    file_id = m.group()
    for f in files_in_set_b:
        if file_id in f:
            return os.path.join("/content/drive/MyDrive/dataset/set_b", f)
    return None

df = df.dropna(subset=[label_colB])
df["audio_path"] = df[file_colB].apply(get_audio_path)
df["exists"] = df["audio_path"].apply(lambda p: p is not None and os.path.exists(p))
df = df[df["exists"]]

samples = df.groupby(label_colB).sample(
    n=3,
    random_state=42
)

plt.figure(figsize=(16,20))

for i, (_, row) in enumerate(samples.iterrows(), start=1):
    audio_path = row["audio_path"]
    try:
        y, sr = librosa.load(audio_path, sr=None)
    except Exception as e:
        print(f"Skip {audio_path}: {e}")
        continue

    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)
    mel_db = librosa.power_to_db(mel, ref=np.max)

    plt.subplot(len(samples), 1, i)
    librosa.display.specshow(mel_db, sr=sr, x_axis="time", y_axis="mel")
    plt.title(f"{row[label_colB]} | {os.path.basename(audio_path)}")
    plt.colorbar(format="%+2.0f dB")

plt.tight_layout()
plt.show()

# set B - sampling rate

audio_folder = "/content/drive/MyDrive/dataset/set_b"

sampling_rates = []

for file in os.listdir(audio_folder):

    if file.endswith(".wav"):

        path = os.path.join(audio_folder, file)

        try:
            sr = librosa.get_samplerate(path)
            sampling_rates.append(sr)

        except Exception as e:
            print(f"Error: {file}")

print("Sampling Rate Distribution")
print(Counter(sampling_rates))

"""***THE CIRCOR***"""

import zipfile

zip_path = "/content/drive/MyDrive/the-circor-digiscope-phonocardiogram-dataset-1.0.3.zip"

extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:

    zip_ref.extractall(extract_path)

print("Extracted!")

# circor - random

Audio("/content/drive/MyDrive/dataset/the-circor/training_data/13918_AV.wav")

# circor - dataset size

folder_path = "/content/dataset/the-circor-digiscope-phonocardiogram-dataset-1.0.3/training_data"

wav_files = []
data = []

file_count = 0
total_size = 0

for root, dirs, files in os.walk(folder_path):
    for file in files:
        if file.lower().endswith(".wav"):
            full_path = os.path.join(root, file)
            wav_files.append(full_path)
            file_count += 1
            total_size += os.path.getsize(full_path)
            label = os.path.basename(root)
            data.append({
                "fname": full_path,
                "label": label
            })

df = pd.DataFrame(data)
print(df.head())

total_size_mb = total_size / (1024 * 1024)
print("=== DATASET SIZE ===")
print("Total wav files:", len(wav_files))
print("Total size:", round(total_size_mb, 2), "MB")

metadata = pd.read_csv("/content/dataset/the-circor-digiscope-phonocardiogram-dataset-1.0.3/training_data.csv")
counts = metadata["Murmur"].value_counts()
print(counts)

# circor - plot pie chart

plt.figure(figsize=(6,6))
plt.pie(
    counts.values,
    labels=counts.index,
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Murmur Distribution")
plt.show()

# circor - spectrogram

samples = metadata.groupby("Murmur").sample(
    n=3,
    random_state=42
)

plt.figure(figsize=(15,25))
plot_idx = 1

for _, row in samples.iterrows():

    patient_id = str(row["Patient ID"])

    wav_files = glob.glob(
        os.path.join(
            folder_path,
            f"{patient_id}_*.wav"
        )
    )

    if len(wav_files) == 0:
        continue
    wav_path = wav_files[0]
    y, sr = librosa.load(
        wav_path,
        sr=None
    )
    mel_spec = librosa.feature.melspectrogram(
        y=y,
        sr=sr,
        n_mels=128
    )
    mel_db = librosa.power_to_db(
        mel_spec,
        ref=np.max
    )
    plt.subplot(9,1,plot_idx)
    librosa.display.specshow(
        mel_db,
        sr=sr,
        x_axis="time",
        y_axis="mel"
    )
    plt.colorbar(format="%+2.0f dB")
    plt.title(f"Patient {patient_id} | Murmur = {row['Murmur']}")
    plot_idx += 1

plt.tight_layout()
plt.show()

# circor - sampling rate

audio_folder = "/content/dataset/the-circor-digiscope-phonocardiogram-dataset-1.0.3/training_data"

sampling_rates = []

for file in os.listdir(audio_folder):

    if file.endswith(".wav"):

        path = os.path.join(audio_folder, file)

        try:
            sr = librosa.get_samplerate(path)
            sampling_rates.append(sr)

        except Exception as e:
            print(f"Error: {file}")

print("Sampling Rate Distribution")
print(Counter(sampling_rates))