# -*- coding: utf-8 -*-
"""Classifying Heart Sounds 2 dataset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JicZ2VnazsJOcSXhx3f3Fdk5wEKnTXfc
"""

#e
!pip install librosa

#e
!pip install evaluate

#e
import os
import pandas as pd
import numpy as np
import librosa
import soundfile as sf
import torch
import evaluate
from sklearn.metrics import fbeta_score
import matplotlib.pyplot as plt
import seaborn as sns
import torch.nn.functional as F

#e
from IPython.display import Audio
from datasets import Dataset, Features, ClassLabel, Audio
from pathlib import Path
from sklearn.model_selection import train_test_split
from transformers import AutoFeatureExtractor, AutoModelForAudioClassification
from huggingface_hub import notebook_login
from torch.utils.data import DataLoader
from tqdm import tqdm
from transformers import TrainingArguments,Trainer
from transformers import AutoFeatureExtractor,AutoModelForAudioClassification
from evaluate import load
from sklearn.metrics import precision_recall_fscore_support,accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from scipy.special import softmax
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

#e
!pip install git+https://github.com/huggingface/transformers

#1
from google.colab import drive
drive.mount('/content/drive')

#2
mounted_path = "/content/drive/MyDrive/dataset"
dataset_a = os.path.join(mounted_path, "set_a")
dataset_b = os.path.join(mounted_path, "set_b")

#3
meta_data_a = pd.DataFrame(os.listdir(dataset_a), columns = ['filename'])
meta_data_b = pd.DataFrame(os.listdir(dataset_b), columns = ['filename'])

meta_data_a['label'] = meta_data_a['filename'].apply(lambda x: x.split('_')[0])
meta_data_b['label'] = meta_data_b['filename'].apply(lambda x: x.split('_')[0])

#4
meta_data_a['label'] = np.where(meta_data_a['label'] == 'murmur', 'murmur',
                       np.where(meta_data_a['label'] == 'Aunlabelledtest', 'test_set', "non-murmur"))
meta_data_a['filename'] = meta_data_a['filename'].apply(lambda x: os.path.join(mounted_path, "set_a", x))

meta_data_b['label'] = np.where(meta_data_b['label'] == 'murmur', 'murmur',
                       np.where(meta_data_b['label'] == 'Bunlabelledtest', 'test_set', "non-murmur"))
meta_data_b['filename'] = meta_data_b['filename'].apply(lambda x: os.path.join(mounted_path, "set_b", x))

total_dataset = pd.concat([meta_data_a, meta_data_b], ignore_index = True)

test_dataset = total_dataset[total_dataset['label'] == 'test_set'].reset_index(drop = True)
total_train_dataset = total_dataset[total_dataset['label'] != 'test_set']

#5
unique_labels = total_train_dataset['label'].unique().tolist()
unique_labels.sort()

features = Features({
    'filename': Audio(sampling_rate=16000), # Assuming a target sampling rate, adjust if necessary
    'label': ClassLabel(names=unique_labels)
})

hf_dataset = Dataset.from_pandas(total_train_dataset.reset_index(drop = True), features=features)

print(hf_dataset)
print(hf_dataset[0])

#6
label_feature = hf_dataset.features['label']

print("Integer ID to String Label Mapping:")
for i, name in enumerate(label_feature.names):
    print(f"ID {i}: {name}")

first_sample_label_id = hf_dataset[0]['label']
first_sample_label_str = label_feature.int2str(first_sample_label_id)
print(f"\nLabel ID for the first sample: {first_sample_label_id}")
print(f"String label for the first sample: {first_sample_label_str}")

"""***The Circor***"""

#1
df = pd.read_csv("/content/drive/MyDrive/dataset/the-circor/training_data.csv")
print(df['Murmur'].value_counts())

#2#3#4
mounted_path = "/content/drive/MyDrive/dataset"

df_meta = pd.read_csv(os.path.join(mounted_path, "the-circor", "training_data.csv"))
df_meta['label'] = np.where(df_meta['Murmur'] == 'Present', 'murmur',
                   np.where(df_meta['Murmur'] == 'Absent' , 'non-murmur',
                   np.where(df_meta['Murmur'] == 'Unknown' , 'test_set' , 'non-murmur')))

wav_dir = os.path.join(mounted_path, "the-circor", "training_data")
wav_files = [os.path.join(wav_dir , f) for f in os.listdir(wav_dir)
             if f.endswith('.wav')]

df_wav = pd.DataFrame(wav_files, columns=['filename'])
df_wav['Patient ID'] = df_wav['filename'].apply(
    lambda x: int(os.path.basename(x).split('_')[0])
)

df_final = df_wav.merge(df_meta[['Patient ID', 'label', 'Murmur']], on='Patient ID', how='left')
df_final = df_final[df_final['label'] != 'test_set'].reset_index(drop=True)

print(df_final.head(20))

#5
unique_labels = df_final['label'].unique().tolist()
unique_labels.sort()

features = Features({
    'filename': Audio(sampling_rate=16000), # Assuming a target sampling rate, adjust if necessary
    'label': ClassLabel(names=unique_labels)
})

df_for_hf = df_final[['filename', 'label']].reset_index(drop=True)
hf_dataset = Dataset.from_pandas(df_for_hf, features=features)

print(hf_dataset)
print(hf_dataset[0])

#6
label_feature = hf_dataset.features['label']

print("Integer ID to String Label Mapping:")
for i, name in enumerate(label_feature.names):
    print(f"ID {i}: {name}")

first_sample_label_id = hf_dataset[0]['label']
first_sample_label_str = label_feature.int2str(first_sample_label_id)
print(f"\nLabel ID for the first sample: {first_sample_label_id}")
print(f"String label for the first sample: {first_sample_label_str}")

"""**Combine**"""

#e
total_train_dataset['filename'] = total_train_dataset['filename'].apply( lambda x: os.path.join(mounted_path, "the-dataset", x) )
df_final['filename'] = df_final['filename'].apply( lambda x: os.path.join(mounted_path, "the-circor", x) )
combined_dataset = pd.concat([total_train_dataset, df_final], ignore_index = True)

#e
combined_dataset['label'].value_counts()

#e
def clean_audio(
    input_path: str,
    output_path: str,
    top_db: float = 20.0,
    target_lufs: float = -23.0,
):
    input_path = Path(input_path)
    output_path = Path(output_path)

    y, sr = librosa.load(str(input_path), sr=None, mono=False)
    original_length = y.shape[-1]

    if y.ndim == 2:
        y_mono = librosa.to_mono(y)
    else:
        y_mono = y

    y_mono = np.nan_to_num(y_mono, nan=0.0, posinf=0.0, neginf=0.0)

    _, intervals = librosa.effects.trim(y_mono, top_db=top_db)
    start, end = intervals[0], intervals[1]

    if y.ndim == 2:
        y_trimmed = y[:, start:end]
    else:
        y_trimmed = y[start:end]

    trimmed_length = y_trimmed.shape[-1]
    pad_width = original_length - trimmed_length

    if pad_width > 0:
        if y.ndim == 2:
            y_padded = np.pad(y_trimmed, ((0, 0), (0, pad_width)), mode="constant")
        else:
            y_padded = np.pad(y_trimmed, (0, pad_width), mode="constant")
    else:
        y_padded = y_trimmed[..., :original_length]

    y_padded = np.nan_to_num(y_padded, nan=0.0, posinf=0.0, neginf=0.0)

    rms = np.sqrt(np.mean(y_padded ** 2))

    if rms > 0:
        target_rms = 10 ** (target_lufs / 20.0)
        gain = target_rms / rms
        y_normalized = np.clip(y_padded * gain, -1.0, 1.0)
    else:
        y_normalized = y_padded

    if y_normalized.ndim == 2:
        y_out = y_normalized.T
    else:
        y_out = y_normalized

    output_path.parent.mkdir(parents=True, exist_ok=True)
    sf.write(str(output_path), y_out, sr)

    print(f"Done: {input_path.name}")
    print(f"Original length : {original_length / sr:.3f}s")
    print(f"Trimmed content : {trimmed_length / sr:.3f}s")
    print(f"Pad added       : {pad_width / sr:.3f}s")
    print(f"RMS before      : {rms:.6f}")
    print(f"Saved to        : {output_path}")

def batch_clean(input_dir: str, output_dir: str, extensions=(".wav", ".flac", ".mp3")):
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    files = [
        f for f in input_dir.rglob("*")
        if f.suffix.lower() in extensions
    ]
    print(f"Found {len(files)} file(s) in {input_dir}\n")

    for f in files:
        out = output_dir / f.relative_to(input_dir).with_suffix(".wav")
        out.parent.mkdir(parents=True, exist_ok=True)
        try:
            clean_audio(str(f), str(out))
        except Exception as e:
            print(f"Error {f.name}: {e}")

combined_dataset = combined_dataset.dropna(subset=["filename"])
folders = (
    combined_dataset["filename"]
    .apply(lambda x: os.path.dirname(str(x)))
    .dropna()
    .unique()
)
for folder in folders:
    if folder and os.path.exists(folder):
        batch_clean(folder, os.path.join(mounted_path, "cleaned_audio"))
    else:
        print(f"Skip invalid folder: {folder}")

#e
murmur_df = combined_dataset[combined_dataset['label'] == 'murmur']
non_murmur_df = combined_dataset[combined_dataset['label'] == 'non-murmur']

n_murmur = len(murmur_df)
n_non_murmur_target = round(n_murmur * 70 / 30)
non_murmur_sampled = non_murmur_df.sample(n=n_non_murmur_target, random_state=42)
combined_dataset = pd.concat([murmur_df, non_murmur_sampled]).reset_index(drop=True)
combined_dataset = combined_dataset.sample(frac=1, random_state=42).reset_index(drop=True)

print(combined_dataset['label'].value_counts())

"""***Training Model***"""

#e
train_valid_dataset, test_dataset = train_test_split(
    combined_dataset,
    test_size=0.15,
    random_state=42,
    stratify=combined_dataset['label']
)
train_dataset, valid_dataset = train_test_split(
    train_valid_dataset,
    test_size=0.2,
    random_state=42,
    stratify=train_valid_dataset['label']
)
train_dataset = train_dataset.reset_index(drop=True)
valid_dataset = valid_dataset.reset_index(drop=True)
test_dataset  = test_dataset.reset_index(drop=True)

print("Train:", train_dataset['label'].value_counts())
print("Valid:", valid_dataset['label'].value_counts())
print("Test:",  test_dataset['label'].value_counts())

#e
unique_labels = combined_dataset['label'].unique().tolist()
unique_labels.sort()
features = Features({
    'filename': Audio(sampling_rate=16000),
    'label': ClassLabel(names=unique_labels)
})
hf_train_dataset = Dataset.from_pandas(
    train_dataset[['filename', 'label']].reset_index(drop=True),
    features=features
)
hf_valid_dataset = Dataset.from_pandas(
    valid_dataset[['filename', 'label']].reset_index(drop=True),
    features=features
)
hf_test_dataset = Dataset.from_pandas(
    test_dataset[['filename', 'label']].reset_index(drop=True),
    features=features
)
print(hf_train_dataset)
print(hf_valid_dataset)
print(hf_test_dataset)

"""***MODEL 1***"""

### model 1

model_name = "Vladimirlv/ast-finetuned-audioset-10-10-0.4593-heart-sounds"
feature_extractor = AutoFeatureExtractor.from_pretrained(
    model_name,
    do_normalize=True,
    return_attention_mask=True
)
model = AutoModelForAudioClassification.from_pretrained(
    model_name,
    num_labels=len(unique_labels),
    ignore_mismatched_sizes=True,
    hidden_dropout_prob=0.1,
    attention_probs_dropout_prob=0.1
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

def preprocess_function(examples):
    # Extract the 'array' from the Audio feature
    audio_arrays = [x["array"] for x in examples["filename"]]
    inputs = feature_extractor(
        audio_arrays,
        sampling_rate=feature_extractor.sampling_rate,
        max_length=16000,
        truncation=True,
        padding="max_length",
        return_tensors="pt"
    )
    return inputs

# Map the dataset. Note: Audio decoding happens on CPU.
# We'll remove the original 'filename' column to save memory after extraction.
hf_train_dataset = hf_train_dataset.map(preprocess_function, batched=True, batch_size=100)
hf_valid_dataset = hf_valid_dataset.map(preprocess_function, batched=True, batch_size=100)
hf_test_dataset = hf_test_dataset.map(preprocess_function, batched=True, batch_size=100)

# Move model to GPU
model.to(device)

from sklearn.metrics import (
    precision_recall_fscore_support,
    accuracy_score
)
from transformers import (
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
    TrainerCallback
)
from torch.optim.lr_scheduler import ReduceLROnPlateau

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted",
        zero_division=0
    )
    accuracy = accuracy_score(
        labels,
        predictions
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

class ReduceLROnPlateauCallback(TrainerCallback):
    def __init__(
        self,
        factor=0.5,
        patience=1,
        min_lr=1e-7
    ):
        self.factor = factor
        self.patience = patience
        self.min_lr = min_lr
        self.scheduler = None

    def on_train_begin(
        self,
        args,
        state,
        control,
        **kwargs
    ):

        optimizer = kwargs["optimizer"]
        self.scheduler = ReduceLROnPlateau(
            optimizer,
            mode="min",
            factor=self.factor,
            patience=self.patience,
            min_lr=self.min_lr
        )

    def on_evaluate(
        self,
        args,
        state,
        control,
        metrics,
        **kwargs
    ):
        if "eval_loss" in metrics:
            self.scheduler.step(
                metrics["eval_loss"]
            )

output_path = "./results/"
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-6,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=8,
    weight_decay=0.1,
    warmup_ratio=0.05,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2
    )

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=hf_train_dataset,
    eval_dataset=hf_valid_dataset,
    compute_metrics=compute_metrics,
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=2
        ),
        ReduceLROnPlateauCallback(
            factor=0.5,
            patience=1,
            min_lr=1e-7
        )
    ]

    )
trainer.train()

saved_model_path = "/content/drive/MyDrive/dataset/model_artifacts"

os.makedirs(saved_model_path, exist_ok=True)

print(f"Saving model artifacts to {saved_model_path}...")
model.save_pretrained(saved_model_path)
feature_extractor.save_pretrained(saved_model_path)

trainer.save_model(saved_model_path)
trainer.save_state()

print("Model artifacts saved successfully.")

model.save_pretrained("./heart_sound_model")
feature_extractor.save_pretrained("./heart_sound_model")

from huggingface_hub import notebook_login
notebook_login()

repo_id = "ParasaPicha/heart-sound-classifierfinal04"
model.push_to_hub(repo_id)
feature_extractor.push_to_hub(repo_id)

def eval_model(model, hf_valid_dataset, feature_extractor=None, batch_size=8, device="cuda"):
    model.eval()
    model.to(device)

    valid_loader = DataLoader(
        hf_valid_dataset,
        batch_size=batch_size,
        shuffle=False
    )
    total = 0
    correct = 0
    total_loss = 0.0

    loss_fn = torch.nn.CrossEntropyLoss()
    with torch.no_grad():
        for batch in tqdm(valid_loader, desc="Evaluating"):
            # common HF dataset keys: input_values / pixel_values / input_features
            if "input_values" in batch:
                inputs = batch["input_values"].to(device)
                outputs = model(input_values=inputs, labels=batch["label"].to(device))
            elif "pixel_values" in batch:
                inputs = batch["pixel_values"].to(device)
                outputs = model(pixel_values=inputs, labels=batch["label"].to(device))
            elif "input_features" in batch:
                inputs = batch["input_features"].to(device)
                outputs = model(input_features=inputs, labels=batch["label"].to(device))
            else:
                raise ValueError(f"Unknown input keys: {batch.keys()}")

            labels = batch["label"].to(device)
            loss = outputs.loss
            logits = outputs.logits
            preds = torch.argmax(logits, dim=-1)
            total_loss += loss.item()
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    avg_loss = total_loss / len(valid_loader)
    accuracy = correct / total
    return {
        "eval_loss": avg_loss,
        "eval_accuracy": accuracy
    }

### check train_set
train_evaler = Trainer(
    model=model,
    args=training_args,
    eval_dataset=hf_train_dataset,
    compute_metrics=compute_metrics,
)
train_results = train_evaler.evaluate()
print("Train Results:", train_results)

### check test_set
test_evaler = Trainer(
    model=model,
    args=training_args,
    eval_dataset=hf_test_dataset,
    compute_metrics=compute_metrics,
)
test_results = test_evaler.evaluate()
print("Test Results:", test_results)

"""***MODEL 2***"""

###model 2

feature_extractor = AutoFeatureExtractor.from_pretrained("facebook/hubert-base-ls960")
model = AutoModelForAudioClassification.from_pretrained(
    "facebook/hubert-base-ls960",
    num_labels=2
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
def preprocess_function(examples):
    audio_arrays = [
        x["array"] for x in examples["filename"]
    ]
    inputs = feature_extractor(
        audio_arrays,
        sampling_rate=16000,
        max_length=16000,
        truncation=True,
        padding=True
    )
    inputs["labels"] = examples["label"]
    return inputs

hf_train_dataset = hf_train_dataset.map(
    preprocess_function,
    batched=True,
    batch_size=100,
    remove_columns=hf_train_dataset.column_names
)
hf_valid_dataset = hf_valid_dataset.map(
    preprocess_function,
    batched=True,
    batch_size=100,
    remove_columns=hf_valid_dataset.column_names
)
hf_test_dataset = hf_test_dataset.map(
    preprocess_function,
    batched=True,
    batch_size=100,
    remove_columns=hf_test_dataset.column_names
)
model.to(device)

metric = load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
    labels, predictions, average='weighted', zero_division=0
    )
    accuracy = accuracy_score(labels, predictions)

    return metric.compute(predictions=predictions, references=labels) | {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "accuracy": accuracy,
    }

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-6,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=8,
    warmup_ratio=0.1,
    logging_dir="./logs",
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    weight_decay=0.05,
)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=hf_train_dataset,
    eval_dataset=hf_valid_dataset,
    compute_metrics=compute_metrics,
)
trainer.train()

saved_model_path = "/content/drive/MyDrive/dataset/model_artifactNUM2"
os.makedirs(saved_model_path, exist_ok=True)

print(f"Saving model artifacts to {saved_model_path}...")
model.save_pretrained(saved_model_path)
feature_extractor.save_pretrained(saved_model_path)

trainer.save_model(saved_model_path)
trainer.save_state()
print("Model artifacts saved successfully.")

model.save_pretrained("./heart_sound_model")
feature_extractor.save_pretrained("./heart_sound_model")

repo_id = "ParasaPicha/heart-sound-classifierHubert02"
model.push_to_hub(repo_id)
feature_extractor.push_to_hub(repo_id)

def eval_model(model, hf_valid_dataset, feature_extractor=None, batch_size=8, device="cuda"):
    model.eval()
    model.to(device)

    valid_loader = DataLoader(
        hf_valid_dataset,
        batch_size=batch_size,
        shuffle=False
    )
    total = 0
    correct = 0
    total_loss = 0.0
    loss_fn = torch.nn.CrossEntropyLoss()
    with torch.no_grad():
        for batch in tqdm(valid_loader, desc="Evaluating"):
            # common HF dataset keys: input_values / pixel_values / input_features
            if "input_values" in batch:
                inputs = batch["input_values"].to(device)
                outputs = model(input_values=inputs, labels=batch["label"].to(device))
            elif "pixel_values" in batch:
                inputs = batch["pixel_values"].to(device)
                outputs = model(pixel_values=inputs, labels=batch["label"].to(device))
            elif "input_features" in batch:
                inputs = batch["input_features"].to(device)
                outputs = model(input_features=inputs, labels=batch["label"].to(device))
            else:
                raise ValueError(f"Unknown input keys: {batch.keys()}")

            labels = batch["label"].to(device)
            loss = outputs.loss
            logits = outputs.logits
            preds = torch.argmax(logits, dim=-1)
            total_loss += loss.item()
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    avg_loss = total_loss / len(valid_loader)
    accuracy = correct / total

    return {
        "eval_loss": avg_loss,
        "eval_accuracy": accuracy
    }

### check train_set
train_evaler = Trainer(
    model=model,
    args=training_args,
    eval_dataset=hf_train_dataset,
    compute_metrics=compute_metrics,
)
train_results = train_evaler.evaluate()
print("Train Results:", train_results)
### check test_set
test_evaler = Trainer(
    model=model,
    args=training_args,
    eval_dataset=hf_test_dataset,
    compute_metrics=compute_metrics,
)
test_results = test_evaler.evaluate()
print("Test Results:", test_results)

"""***MODEL 3***"""

###model 3

model_name = "MIT/ast-finetuned-audioset-10-10-0.4593"
feature_extractor = AutoFeatureExtractor.from_pretrained(
    model_name,
    do_normalize=True,
    return_attention_mask=True
)
model = AutoModelForAudioClassification.from_pretrained(
    model_name,
    num_labels=len(unique_labels),
    ignore_mismatched_sizes=True,
    hidden_dropout_prob=0.1,
    attention_probs_dropout_prob=0.1
)

print(hf_train_dataset.column_names)
print(hf_train_dataset.features)
print(hf_train_dataset[0])

print(hf_train_dataset.column_names)

print(hf_train_dataset)

#e
unique_labels = combined_dataset['label'].unique().tolist()
unique_labels.sort()
features = Features({
    'filename': Audio(sampling_rate=16000),
    'label': ClassLabel(names=unique_labels)
})
hf_train_dataset = Dataset.from_pandas(
    train_dataset[['filename', 'label']].reset_index(drop=True),
    features=features
)
hf_valid_dataset = Dataset.from_pandas(
    valid_dataset[['filename', 'label']].reset_index(drop=True),
    features=features
)
hf_test_dataset = Dataset.from_pandas(
    test_dataset[['filename', 'label']].reset_index(drop=True),
    features=features
)
print(hf_train_dataset)
print(hf_valid_dataset)
print(hf_test_dataset)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

def preprocess_function(examples):
    audio_arrays = [np.array(x["array"]).flatten() for x in examples["filename"]]

    inputs = feature_extractor(
        audio_arrays,
        sampling_rate=feature_extractor.sampling_rate,
        max_length=16000,
        truncation=True,
        padding="max_length",
        return_tensors="pt"
    )
    return inputs

# Map the dataset. Note: Audio decoding happens on CPU.
# We'll remove the original 'filename' column to save memory after extraction.
hf_train_dataset = hf_train_dataset.map(preprocess_function, batched=True, batch_size=100)
hf_valid_dataset = hf_valid_dataset.map(preprocess_function, batched=True, batch_size=100)
hf_test_dataset = hf_test_dataset.map(preprocess_function, batched=True, batch_size=100)

# Move model to GPU
model.to(device)

from sklearn.metrics import (
    precision_recall_fscore_support,
    accuracy_score
)
from transformers import (
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
    TrainerCallback
)
from torch.optim.lr_scheduler import ReduceLROnPlateau
metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted",
        zero_division=0
    )
    accuracy = accuracy_score(
        labels,
        predictions
    )
    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }
class ReduceLROnPlateauCallback(TrainerCallback):
    def __init__(
        self,
        factor=0.5,
        patience=1,
        min_lr=1e-7
    ):
        self.factor = factor
        self.patience = patience
        self.min_lr = min_lr
        self.scheduler = None

    def on_train_begin(
        self,
        args,
        state,
        control,
        **kwargs
    ):
        optimizer = kwargs["optimizer"]
        self.scheduler = ReduceLROnPlateau(
            optimizer,
            mode="min",
            factor=self.factor,
            patience=self.patience,
            min_lr=self.min_lr
        )
    def on_evaluate(
        self,
        args,
        state,
        control,
        metrics,
        **kwargs
    ):
        if "eval_loss" in metrics:
            self.scheduler.step(
                metrics["eval_loss"]
            )
training_args = TrainingArguments(
    output_dir=f"./results/",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-6,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.1,
    warmup_ratio=0.05,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=2
    )

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=hf_train_dataset,
    eval_dataset=hf_valid_dataset,
    compute_metrics=compute_metrics,
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=1
        ),
        ReduceLROnPlateauCallback(
            factor=0.5,
            patience=1,
            min_lr=1e-7
        )
    ]
)
trainer.train()

saved_model_path = "/content/drive/MyDrive/dataset/model_artifacts-astbase"
os.makedirs(saved_model_path, exist_ok=True)
print(f"Saving model artifacts to {saved_model_path}...")
model.save_pretrained(saved_model_path)
feature_extractor.save_pretrained(saved_model_path)
trainer.save_model(saved_model_path)
trainer.save_state()

print("Model artifacts saved successfully.")

model.save_pretrained("./heart_sound_model")
feature_extractor.save_pretrained("./heart_sound_model")

repo_id = "ParasaPicha/heart-sound-classifier-astbase06"
model.push_to_hub(repo_id)
feature_extractor.push_to_hub(repo_id)

def eval_model(model, hf_valid_dataset, feature_extractor=None, batch_size=8, device="cuda"):
    model.eval()
    model.to(device)
    valid_loader = DataLoader(
        hf_valid_dataset,
        batch_size=batch_size,
        shuffle=False
    )
    total = 0
    correct = 0
    total_loss = 0.0

    loss_fn = torch.nn.CrossEntropyLoss()
    with torch.no_grad():
        for batch in tqdm(valid_loader, desc="Evaluating"):
            # common HF dataset keys: input_values / pixel_values / input_features
            if "input_values" in batch:
                inputs = batch["input_values"].to(device)
                outputs = model(input_values=inputs, labels=batch["label"].to(device))
            elif "pixel_values" in batch:
                inputs = batch["pixel_values"].to(device)
                outputs = model(pixel_values=inputs, labels=batch["label"].to(device))
            elif "input_features" in batch:
                inputs = batch["input_features"].to(device)
                outputs = model(input_features=inputs, labels=batch["label"].to(device))
            else:
                raise ValueError(f"Unknown input keys: {batch.keys()}")

            labels = batch["label"].to(device)
            loss = outputs.loss
            logits = outputs.logits
            preds = torch.argmax(logits, dim=-1)
            total_loss += loss.item()
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    avg_loss = total_loss / len(valid_loader)
    accuracy = correct / total

    return {
        "eval_loss": avg_loss,
        "eval_accuracy": accuracy
    }

### check train_set
train_evaler = Trainer(
    model=model,
    args=training_args,
    eval_dataset=hf_train_dataset,
    compute_metrics=compute_metrics,
)
train_results = train_evaler.evaluate()
print("Train Results:", train_results)
### check test_set
test_evaler = Trainer(
    model=model,
    args=training_args,
    eval_dataset=hf_test_dataset,
    compute_metrics=compute_metrics,
)
test_results = test_evaler.evaluate()
print("Test Results:", test_results)

"""**ERROR ANALYSIS MODEL 1**"""

model_name = "ParasaPicha/heart-sound-classifierfinal03"

model = AutoModelForAudioClassification.from_pretrained(model_name)
feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)

training_args = TrainingArguments(
    output_dir="./output",
    per_device_eval_batch_size=8,
)
trainer = Trainer(
    model=model,
    args=training_args,
    processing_class=feature_extractor,
)
predictions = trainer.predict(hf_valid_dataset)

predictions = trainer.predict(hf_valid_dataset)
logits = predictions.predictions
y_valid = predictions.label_ids

probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
prob_positive = probs[:, 1]

best_threshold, best_f2 = 0.5, 0
for t in np.arange(0.05, 0.95, 0.005):
    preds = (prob_positive >= t).astype(int)
    score = fbeta_score(y_valid, preds, beta=2, zero_division=0)
    if score > best_f2:
        best_f2, best_threshold = score, t

print(f"Best threshold: {best_threshold:.3f}  →  F2={best_f2:.4f}")

test_predictions = trainer.predict(hf_test_dataset)
test_probs = torch.softmax(torch.tensor(test_predictions.predictions), dim=-1).numpy()
final_pred = (test_probs[:, 1] >= best_threshold).astype(int)

model = AutoModelForAudioClassification.from_pretrained(model_name)
feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
model.eval()
MAX_LEN = 16000
X_test_raw = []
for path in test_dataset['filename']:
    audio, sr = librosa.load(path, sr=16000)
    if len(audio) < MAX_LEN:
        audio = np.pad(audio, (0, MAX_LEN - len(audio)))
    else:
        audio = audio[:MAX_LEN]
    X_test_raw.append(audio)

label2id = {'murmur': 0, 'non-murmur': 1}
id2label = {0: 'murmur', 1: 'non-murmur'}
y_test = [label2id[label] for label in test_dataset['label']]
inputs = feature_extractor(
    X_test_raw,
    sampling_rate=16000,
    return_tensors="pt",
    padding=True
)
with torch.no_grad():
    outputs = model(**inputs)
    logits = outputs.logits
probs     = F.softmax(logits, dim=-1)
y_pred    = torch.argmax(probs, dim=-1)
y_pred_np = y_pred.numpy()
y_prob_np = probs.detach().numpy()
labels     = [0, 1]
label_names = ['murmur', 'non-murmur']
report    = classification_report(y_test, y_pred_np, target_names=label_names, output_dict=True)
df_report = pd.DataFrame(report).T
print(df_report[['precision', 'recall', 'f1-score', 'support']])
cm = confusion_matrix(y_test, y_pred_np, labels=labels)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=label_names,
            yticklabels=label_names,
            cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()
df_errors = pd.DataFrame({
    'actual'   : y_test,
    'predicted': y_pred_np,
    'correct'  : np.array(y_test) == y_pred_np
})
for cls in labels:
    errors = df_errors[(df_errors['actual'] == cls) & (~df_errors['correct'])]
    if len(errors) == 0:
        continue
    print(f"\n=== Class: {id2label[cls]} | errors: {len(errors)} / {len(df_errors)} samples ===")
    print(errors['predicted'].map(id2label).value_counts().to_string())
error_ids   = df_errors[~df_errors['correct']].index
correct_ids = df_errors[ df_errors['correct']].index
X_test_np = np.array(X_test_raw)
X_errors  = X_test_np[error_ids]
X_correct = X_test_np[correct_ids]
print(pd.DataFrame({
    'errors' : X_errors.mean(axis=0),
    'correct': X_correct.mean(axis=0)
}))

"""**ERROR ANALYSIS MODEL 2**"""

unique_labels = ['murmur', 'non-murmur']
model_name2 = "ParasaPicha/heart-sound-classifierHubert"

feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
model = AutoModelForAudioClassification.from_pretrained(
    model_name,
    num_labels=len(unique_labels),
    ignore_mismatched_sizes=True
)

model_name2 = "ParasaPicha/heart-sound-classifierHubert"
model = AutoModelForAudioClassification.from_pretrained(model_name)
feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
model.eval()
MAX_LEN = 16000
X_test_raw = []
for path in test_dataset['filename']:
    audio, sr = librosa.load(path, sr=16000)
    if len(audio) < MAX_LEN:
        audio = np.pad(audio, (0, MAX_LEN - len(audio)))
    else:
        audio = audio[:MAX_LEN]
    X_test_raw.append(audio)

label2id = {'murmur': 0, 'non-murmur': 1}
id2label = {0: 'murmur', 1: 'non-murmur'}
y_test = [label2id[label] for label in test_dataset['label']]
inputs = feature_extractor(
    X_test_raw,
    sampling_rate=16000,
    return_tensors="pt",
    padding=True
)
with torch.no_grad():
    outputs = model(**inputs)
    logits = outputs.logits
probs     = F.softmax(logits, dim=-1)
y_pred    = torch.argmax(probs, dim=-1)
y_pred_np = y_pred.numpy()
y_prob_np = probs.detach().numpy()
labels     = [0, 1]
label_names = ['murmur', 'non-murmur']
report    = classification_report(y_test, y_pred_np, target_names=label_names, output_dict=True)
df_report = pd.DataFrame(report).T
print(df_report[['precision', 'recall', 'f1-score', 'support']])
cm = confusion_matrix(y_test, y_pred_np, labels=labels)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=label_names,
            yticklabels=label_names,
            cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()
df_errors = pd.DataFrame({
    'actual'   : y_test,
    'predicted': y_pred_np,
    'correct'  : np.array(y_test) == y_pred_np
})
for cls in labels:
    errors = df_errors[(df_errors['actual'] == cls) & (~df_errors['correct'])]
    if len(errors) == 0:
        continue
    print(f"\n=== Class: {id2label[cls]} | errors: {len(errors)} / {len(df_errors)} samples ===")
    print(errors['predicted'].map(id2label).value_counts().to_string())
error_ids   = df_errors[~df_errors['correct']].index
correct_ids = df_errors[ df_errors['correct']].index
X_test_np = np.array(X_test_raw)
X_errors  = X_test_np[error_ids]
X_correct = X_test_np[correct_ids]
print("\nMean features — errors vs correct:")
print(pd.DataFrame({
    'errors' : X_errors.mean(axis=0),
    'correct': X_correct.mean(axis=0)
}))

"""**ERROR ANALYSIS MODEL 3**"""

model = AutoModelForAudioClassification.from_pretrained(
    "ParasaPicha/heart-sound-classifier-astbase04",
    num_labels=2,
    ignore_mismatched_sizes=True
)
print("OK")

pred_output = trainer.predict(hf_test_dataset)
logits = pred_output.predictions
labels = pred_output.label_ids
probs = softmax(logits, axis=1)
preds = np.argmax(probs, axis=1)
confidences = probs.max(axis=1)

error_df = pd.DataFrame({
    "path": hf_test_dataset["filename"],
    "true_label": labels,
    "pred_label": preds,
    "confidence": confidences
})
error_df["correct"] = (
    error_df["true_label"] ==
    error_df["pred_label"]
)
errors = error_df[
    error_df["correct"] == False
].copy()
print("Wrong files number = ", len(errors))
display(errors.head())
errors = errors.sort_values(
    "confidence",
    ascending=False
)
display(
    errors[
        ["path",
         "true_label",
         "pred_label",
         "confidence"]
    ].head(20)
)

model_name3 = "ParasaPicha/heart-sound-classifier-astbase04"
model = AutoModelForAudioClassification.from_pretrained(model_name)
feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
model.eval()
MAX_LEN = 16000
X_test_raw = []
for path in test_dataset['filename']:
    audio, sr = librosa.load(path, sr=16000)
    if len(audio) < MAX_LEN:
        audio = np.pad(audio, (0, MAX_LEN - len(audio)))
    else:
        audio = audio[:MAX_LEN]
    X_test_raw.append(audio)

label2id = {'murmur': 0, 'non-murmur': 1}
id2label = {0: 'murmur', 1: 'non-murmur'}
y_test = [label2id[label] for label in test_dataset['label']]
inputs = feature_extractor(
    X_test_raw,
    sampling_rate=16000,
    return_tensors="pt",
    padding=True
)
with torch.no_grad():
    outputs = model(**inputs)
    logits = outputs.logits
probs     = F.softmax(logits, dim=-1)
y_pred    = torch.argmax(probs, dim=-1)
y_pred_np = y_pred.numpy()
y_prob_np = probs.detach().numpy()
labels     = [0, 1]
label_names = ['murmur', 'non-murmur']
report    = classification_report(y_test, y_pred_np, target_names=label_names, output_dict=True)
df_report = pd.DataFrame(report).T
print(df_report[['precision', 'recall', 'f1-score', 'support']])
cm = confusion_matrix(y_test, y_pred_np, labels=labels)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=label_names,
            yticklabels=label_names,
            cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()
df_errors = pd.DataFrame({
    'actual'   : y_test,
    'predicted': y_pred_np,
    'correct'  : np.array(y_test) == y_pred_np
})
for cls in labels:
    errors = df_errors[(df_errors['actual'] == cls) & (~df_errors['correct'])]
    if len(errors) == 0:
        continue
    print(f"\n=== Class: {id2label[cls]} | errors: {len(errors)} / {len(df_errors)} samples ===")
    print(errors['predicted'].map(id2label).value_counts().to_string())

pred_output = trainer.predict(hf_test_dataset)
logits = pred_output.predictions
labels = pred_output.label_ids
probs = softmax(logits, axis=1)
preds = np.argmax(probs, axis=1)
confidences = probs.max(axis=1)
error_df = pd.DataFrame({
    "path": hf_test_dataset["filename"],
    "true_label": labels,
    "pred_label": preds,
    "confidence": confidences
})
error_df["correct"] = (
    error_df["true_label"] ==
    error_df["pred_label"]
)
errors = error_df[
    error_df["correct"] == False
].copy()
print("error files number =", len(errors))
display(errors.head())
errors = errors.sort_values(
    "confidence",
    ascending=False
)
display(
    errors[
        ["path",
         "true_label",
         "pred_label",
         "confidence"]
    ].head(20)
)

"""# ***MODEL 3***-ParasaPicha/heart-sound-classifier-astbase04

***loading Model 3***
"""

unique_labels = ['murmur', 'non-murmur']
model_name = "ParasaPicha/heart-sound-classifier-astbase04"

feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
model = AutoModelForAudioClassification.from_pretrained(
    model_name,
    num_labels=len(unique_labels),
    ignore_mismatched_sizes=True
)

# check best checkpoint
import os
print(os.listdir("./results"))

model = AutoModelForAudioClassification.from_pretrained(
    "./results/checkpoint-1266"
)
model.eval()

"""***Threshold***"""

predictions = trainer.predict(hf_valid_dataset)
logits = predictions.predictions
labels = predictions.label_ids
probs = softmax(logits, axis=1)[:, 1]

best_threshold = 0.5
best_recall = 0

print("Searching threshold...")

for threshold in np.arange(0.05, 1.00, 0.05):
    preds = (probs >= threshold).astype(int)
    recall = recall_score(labels, preds)
    print(
        f"Threshold={threshold:.2f} "
        f"Recall={recall:.4f}"
    )
    if recall > best_recall:
        best_recall = recall
        best_threshold = threshold

print("\n====================")
print("Best Threshold:", best_threshold)
print("Best Recall:", best_recall)
print("====================")

predictions = trainer.predict(hf_valid_dataset)
logits = predictions.predictions
labels = predictions.label_ids
probs = softmax(logits, axis=1)[:,1]

best_threshold = 0.5
best_f1 = 0

for threshold in np.arange(0.05,1.00,0.05):
    preds = (probs >= threshold).astype(int)
    f1 = f1_score(labels,preds)
    print(
        f"Threshold={threshold:.2f} "
        f"F1={f1:.4f}"
    )
    if f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold

print("\nBest Threshold =", best_threshold)
print("Best F1 =", best_f1)

predictions = trainer.predict(hf_valid_dataset)
logits = predictions.predictions
labels = predictions.label_ids
probs = softmax(logits, axis=1)[:,1]

best_threshold = 0.5
best_f1 = 0

print(
    f"{'Threshold':<12}"
    f"{'Precision':<12}"
    f"{'Recall':<12}"
    f"{'F1':<12}"
)

for threshold in np.arange(0.05,1.00,0.05):
    preds = (probs >= threshold).astype(int)
    precision = precision_score(labels,preds)
    recall = recall_score(labels,preds)
    f1 = f1_score(labels,preds)
    print(
        f"{threshold:<12.2f}"
        f"{precision:<12.4f}"
        f"{recall:<12.4f}"
        f"{f1:<12.4f}"
    )
    if f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold

print("\nBest Threshold =", best_threshold)
print("Best F1 =", best_f1)

pred_output = trainer.predict(hf_test_dataset)
logits = pred_output.predictions
labels = pred_output.label_ids

probs = torch.softmax(
    torch.tensor(logits),
    dim=1
).numpy()

murmur_probs = probs[:, 1]
best_threshold = 0.4

predictions = (
    murmur_probs >= best_threshold
).astype(int)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
accuracy = accuracy_score(
    labels,
    predictions
)
precision = precision_score(
    labels,
    predictions
)
recall = recall_score(
    labels,
    predictions
)
f1 = f1_score(
    labels,
    predictions
)
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1       :", f1)

cm = confusion_matrix(
    labels,
    predictions
)
plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

murmur_idx = np.where(
    predictions == 0
)[0]
print("murmur =", len(murmur_idx))
